from fpdf import FPDF
import os
from datetime import datetime
import re

class ProfessionalPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.report_id = f"RPT-{datetime.now().strftime('%y%m%d')}-{datetime.now().strftime('%H%M')}"
        self.set_margins(15, 15, 15)
        self.set_auto_page_break(True, margin=15)
    
    def header(self):
        # Page Border
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.5)
        self.rect(5, 5, 200, 287)
        
        # Top Header Bar (White background, Clean Layout)
        # Left: Logo
        self.set_y(15)
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(0, 51, 102) # Dark Medical Blue
        self.cell(0, 10, "Astrameds", 0, 1, 'L')
        
        # Right: Tagline (Aligned with Logo logic, but FPDF header static logic is tricky)
        # We use absolute positioning for header elements to be safe
        self.set_xy(100, 17)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(100, 100, 100) # Grey
        self.cell(0, 10, "AI-Powered Clinical Decision Support", 0, 0, 'R')
        
        # Title Below
        self.set_xy(15, 30)
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, "CLINICAL RISK REPORT", 0, 0, 'L')
        
        # Meta Info Box (Top Right)
        self.set_xy(140, 30)
        self.set_fill_color(245, 245, 245)
        self.set_draw_color(220, 220, 220)
        self.rect(140, 28, 60, 16, 'FD')
        
        self.set_xy(142, 30)
        self.set_font('Helvetica', 'B', 8)
        self.set_text_color(50, 50, 50)
        self.cell(25, 4, "Date:", 0, 0)
        self.set_font('Helvetica', '', 8)
        self.cell(0, 4, datetime.now().strftime('%b %d, %Y'), 0, 1)
        
        self.set_x(142)
        self.set_font('Helvetica', 'B', 8)
        self.cell(25, 4, "Report ID:", 0, 0)
        self.set_font('Helvetica', '', 8)
        self.cell(0, 4, self.report_id, 0, 1)

        self.ln(20) # Space after header

    def footer(self):
        self.set_y(-20)
        self.set_draw_color(200, 200, 200)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(2)
        
        # Left: Sig
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.cell(90, 5, "Electronically Signed: Astrameds AI", 0, 0, 'L')
        
        # Right: Page
        self.cell(0, 5, f"Page {self.page_no()}", 0, 1, 'R')
        
        # Bottom: Disclaimer
        self.ln(1)
        self.set_font('Helvetica', '', 6)
        self.set_text_color(120, 120, 120)
        disclaimer = ("DISCLAIMER: This report is generated by Astrameds AI (v2.0). "
                      "It is intended solely for reference by licensed healthcare professionals and "
                      "does NOT serve as a medical diagnosis. Clinical correlation is required.")
        self.multi_cell(0, 3, disclaimer, 0, 'C')

    def section_title(self, title):
        self.ln(5)
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(0, 51, 102)
        self.cell(0, 8, title, 0, 1, 'L')
        # Underline
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.5)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(3)

    def draw_tag(self, text, type='neutral'):
        # Minimal pill/tag
        self.set_font('Helvetica', 'B', 7)
        w = self.get_string_width(text) + 6
        h = 5
        x = self.get_x()
        y = self.get_y()
        
        r,g,b = (240, 240, 240)
        txt_r, txt_g, txt_b = (50, 50, 50)
        
        if type == 'high':
            r,g,b = (255, 235, 235) # Light Red
            txt_r, txt_g, txt_b = (180, 0, 0)
        elif type == 'warn':
             r,g,b = (255, 250, 235) # Light Orange
             txt_r, txt_g, txt_b = (150, 100, 0)
             
        self.set_fill_color(r,g,b)
        self.set_text_color(txt_r, txt_g, txt_b)
        # Rounded rect shim: use rect
        self.rect(x, y, w, h, 'F')
        self.cell(w, h, text, 0, 0, 'C')
        self.set_text_color(0,0,0) # Reset

class PDFService:
    def __init__(self, output_dir="backend/pdfs"):
        self.output_dir = os.path.join(os.getcwd(), output_dir)
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_report(self, patient_data: dict, risk_score: float, risk_level: str, llm_summary: str, explanations: list = []) -> str:
        pdf = ProfessionalPDF()
        pdf.add_page()
        
        # --- 1. PATIENT PROFILE ---
        pdf.section_title("PATIENT PROFILE")
        
        # Logic to format values
        def fmt_item(label, value, key):
            # Check abnormal
            is_abnormal = False
            # Simple logic for highlighted demo
            if key == 'bmi' and isinstance(value, (int, float)) and value > 25: is_abnormal = True
            if key == 'HbA1c_level' and isinstance(value, (int, float)) and value > 6.0: is_abnormal = True
            if key == 'blood_glucose_level' and isinstance(value, (int, float)) and value > 140: is_abnormal = True
            if key == 'hypertension' and value in [1, True, 'Yes']: is_abnormal = True
            
            return label, str(value), is_abnormal

        items_col1 = [
            fmt_item("Age", f"{patient_data.get('age')} years", 'age'),
            fmt_item("BMI", f"{patient_data.get('bmi')} kg/m2", 'bmi'),
            fmt_item("Blood Glucose", f"{patient_data.get('blood_glucose_level')} mg/dL", 'blood_glucose_level'),
            fmt_item("Hypertension", "Yes" if patient_data.get('hypertension') else "No", 'hypertension')
        ]
        
        items_col2 = [
            fmt_item("Gender", f"{patient_data.get('gender')}", 'gender'),
            fmt_item("HbA1c", f"{patient_data.get('HbA1c_level')}%", 'HbA1c_level'),
            fmt_item("Smoking", f"{patient_data.get('smoking_history').title()}", 'smoking_history'),
            fmt_item("Heart Disease", "Yes" if patient_data.get('heart_disease') else "No", 'heart_disease')
        ]
        
        # Draw nice 2-col layout
        start_y = pdf.get_y()
        
        def draw_col(items, x_offset):
            pdf.set_xy(x_offset, start_y)
            for label, val, abnormal in items:
                pdf.set_x(x_offset)
                pdf.set_font('Helvetica', 'B', 9)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(35, 6, label, 0, 0, 'L')
                
                pdf.set_font('Helvetica', '', 9)
                pdf.set_text_color(0, 0, 0)
                
                if abnormal:
                    # Highlight
                    cur_x = pdf.get_x()
                    cur_y = pdf.get_y()
                    pdf.draw_tag(val, 'high')
                    pdf.set_xy(cur_x, cur_y) # Reset? No, draw_tag advances.
                    pdf.ln(7) # Next row
                else:
                    pdf.cell(40, 6, val, 0, 1, 'L')
                    pdf.ln(1) # Extra space
        
        draw_col(items_col1, 15)
        draw_col(items_col2, 110)
        
        pdf.set_y(start_y + 35) # Manual spacer
        
        # --- 2. RISK ASSESSMENT ---
        pdf.section_title("RISK ASSESSMENT")
        
        # Center Box
        pdf.set_fill_color(250, 252, 255) # Very light blue
        pdf.set_draw_color(230, 230, 230)
        pdf.rect(15, pdf.get_y(), 180, 45, 'FD')
        
        base_y = pdf.get_y()
        
        # Risk Badge
        pdf.set_xy(25, base_y + 5)
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, "RISK CLASSIFICATION", 0, 1, 'L')
        
        pdf.set_xy(25, base_y + 12)
        pdf.set_font('Helvetica', 'B', 16)
        
        r_col = (40, 167, 69)
        if risk_level.lower() == 'high': r_col = (220, 53, 69)
        elif risk_level.lower() == 'moderate': r_col = (255, 193, 7)
        
        pdf.set_text_color(*r_col)
        pdf.cell(0, 8, risk_level.upper(), 0, 1, 'L')
        
        pdf.set_xy(25, base_y + 20)
        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 6, f"(Model Score: {risk_score:.2f})", 0, 1, 'L')
        
        # VISUAL BAR (Right side of box)
        bar_x = 90
        bar_y = base_y + 12
        bar_w = 90
        bar_h = 6
        
        # Gradient segments
        colors = [(40, 167, 69), (255, 193, 7), (255, 120, 0), (220, 53, 69)]
        seg_w = bar_w / 4
        for i, c in enumerate(colors):
            pdf.set_fill_color(*c)
            pdf.rect(bar_x + (i*seg_w), bar_y, seg_w, bar_h, 'F')
            
        # Pointer
        p_x = bar_x + (risk_score * bar_w)
        p_x = min(p_x, bar_x + bar_w) # Clamp
        pdf.set_fill_color(0, 0, 0)
        pdf.rect(p_x - 1, bar_y - 2, 2, bar_h + 4, 'F')
        
        # Description
        pdf.set_xy(90, bar_y + 10)
        pdf.set_font('Helvetica', '', 8)
        pdf.set_text_color(80, 80, 80)
        desc = "Patient is in the upper quartile of cardiovascular risk." if risk_score > 0.7 else "Patient has moderate risk factors."
        if risk_score < 0.3: desc = "Patient is in the low risk range."
        pdf.multi_cell(90, 3, desc, 0, 'L')
        
        pdf.set_y(base_y + 50)
        
        # --- 3. KEY DRIVERS (New Section) ---
        if explanations:
            pdf.section_title("KEY RISK DRIVERS")
            # Simple Table
            pdf.set_font('Helvetica', 'B', 9)
            pdf.set_fill_color(245, 245, 245)
            pdf.cell(60, 8, "  Factor", 0, 0, 'L', True)
            pdf.cell(40, 8, "Value", 0, 0, 'L', True)
            pdf.cell(80, 8, "Clinical Impact", 0, 1, 'L', True)
            
            pdf.set_font('Helvetica', '', 9)
            for item in explanations:
                feature = item.get('feature', '').replace('_', ' ').title()
                val = str(item.get('feature_value', item.get('value', '-')))
                # Simple logic for status
                status = "Normal"
                
                def safe_float(v):
                    try:
                        return float(v)
                    except (ValueError, TypeError):
                        return None
                
                f_val = safe_float(val)
                
                if f_val is not None:
                    # Mock logic if not provided
                    if 'bmi' in feature.lower() and f_val > 25: status = "Elevated"
                    elif 'glu' in feature.lower() and f_val > 100: status = "High"
                    elif 'a1c' in feature.lower() and f_val > 6: status = "Elevated"
                
                pdf.cell(60, 7, f"  {feature}", 'B', 0)
                pdf.cell(40, 7, f"{val}", 'B', 0)
                
                # Colored dot for status
                pdf.set_font('Helvetica', 'B', 9)
                if status != "Normal":
                    pdf.set_text_color(200, 50, 50)
                else:
                    pdf.set_text_color(50, 150, 50)
                pdf.cell(80, 7, status, 'B', 1)
                pdf.set_text_color(0,0,0) # Reset
                pdf.set_font('Helvetica', '', 9)
            
            pdf.ln(5)

        # --- 4. RECOMMENDATIONS ---
        pdf.add_page()
        pdf.section_title("CLINICAL RECOMMENDATIONS")
        
        # Split LLM Summary Logic
        # Expected format: "**1. Clinical Assessment** ... **2. Recommendations** ..."
        parts = llm_summary.split('**2. Recommendations**')
        assessment_text = parts[0].replace('**1. Clinical Assessment**', '').strip()
        actions_text = parts[1].strip() if len(parts) > 1 else ""
        
        # Assessment
        pdf.set_font('Helvetica', 'B', 10)
        pdf.cell(0, 6, "Clinical Assessment", 0, 1)
        pdf.set_font('Helvetica', '', 10)
        pdf.multi_cell(0, 5, assessment_text)
        pdf.ln(4)
        
        # Actions
        if actions_text:
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(0, 6, "Recommended Actions", 0, 1)
            pdf.set_font('Helvetica', '', 10)
            
            # Simple parser for bullets
            lines = actions_text.split('\n')
            for line in lines:
                line = line.strip()
                if not line: continue
                # Remove bullets
                clean = line.lstrip('-').lstrip('•').strip()
                
                # Draw Box/Icon placeholder
                x = pdf.get_x()
                y = pdf.get_y()
                
                # Small square bullet
                pdf.set_fill_color(0, 51, 102)
                pdf.rect(x + 2, y + 2, 2, 2, 'F')
                
                pdf.set_x(x + 8)
                pdf.multi_cell(0, 5, clean)
                pdf.ln(1)
        
        # Save
        filename = f"Astrameds_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        pdf.output(filepath)
        
        return filename
